### ISSUE TITLE
hook for estimating gas 

### ISSUE THREAD

**Issue by mymphe** [lidofinance/lido-js-sdk#10]
To avoid having to hard-code the gas limits for a transaction, we need a hook that simulates the transaction. As `JsonRpcProvider` does not have a signer, we would also need the public address for an account with some ETH and various tokens, including stETH, wstETH, LDO, etc.

**Comment by kozlovzxc-at-lido** [comment]
Discussed on the call, we will try to implement it in staking widget, if it will go nicely, we will move it to js-sdk
