### ISSUE TITLE
Coinbase wallet now supports Ethereum testnets

### ISSUE THREAD

**Issue by mymphe** [lidofinance/lido-js-sdk#12]
Add support for coinbase on testnets

**Comment by mymphe** [comment]
https://github.com/lidofinance/lido-js-sdk/blob/79bbf453821a11ac42ce44fee243031e3e03ae4b/packages/web3-react/src/context/connectors.tsx#L76

**Comment by kozlovzxc-at-lido** [comment]
Discussed on the call, sending to wallets team 👍  Closing this issue for now
