### ISSUE TITLE
Can't use WalletConnect chain switch / connector

### ISSUE THREAD

**Issue by angeljgomezc** [lidofinance/lido-js-sdk#34]
first of all, love this package, it's probably the best out there for its level of usability and quality of features

I'm using it right now and trying to perform chain switching via WalletConnect but it doesn't work

after updating to the last version (` "@lido-sdk/web3-react": "^1.16.0"`), I can't even use the `useWalletConnector` hook on production/preview builds because it throws errors

This comes from changes made in `web3-react` package to allow chain-switching via WalletConnect: https://github.com/NoahZinsmeister/web3-react/commit/87aeb2a2335d98194b86a330edc17e1522aa6e37

will try to fix this with a PR

**Comment by alx-khramov** [comment]
@angeljgomezc Hi! Sorry for the long wait. I suppose this issue is not actual anymore. If it is actual, feel free to open the issue again.
