### ISSUE TITLE
useSwitchChain

### ISSUE THREAD

**Issue by avsetsin** [lidofinance/lido-js-sdk#4]
It would be great to have a hook to switch chain in a wallet. It would be useful when the wallet is connected to another network. https://docs.metamask.io/guide/rpc-api.html#wallet-switchethereumchain

**Comment by alx-khramov** [comment]
https://github.com/rekmarks/EIPs/blob/3326-create/EIPS/eip-3326.md

**Comment by kozlovzxc-at-lido** [comment]
Will create internal ticket
