### ISSUE TITLE
Add test RPC support

### ISSUE THREAD

**Issue by avsetsin** [lidofinance/lido-js-sdk#7]
It would be useful to support Ganaсhi. Including when metamask is connected to it. It looks like chainId 1337 needs to be supported for this

**Comment by avsetsin** [comment]
It would be useful to support Ganaсhi. Including when metamask is connected to it. It looks like chainId 1337 needs to be supported for this

**Comment by kozlovzxc-at-lido** [comment]
Will create internal ticket
